/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;

import javax.swing.JInternalFrame;

/**
 *
 * @author rodri
 */
public class NewJFrame1 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame1.class.getName());
    public static final Directorio DIRECTORIO = new Directorio();

    static {
        DIRECTORIO.addCiudad("San Luis");
        DIRECTORIO.addCiudad("Villa Mercedes");
    }

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
        for (int i = 0; i < DIRECTORIO.getCiudades().toArray().length; i++) {
            System.out.println("ciudad = " + i + DIRECTORIO.getCiudades().toArray()[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnucliente = new javax.swing.JMenu();
        mniAgregarcliente = new javax.swing.JMenuItem();
        mniBuscarcliente = new javax.swing.JMenuItem();
        mniBorrarcliente = new javax.swing.JMenuItem();
        mnudirectorio = new javax.swing.JMenu();
        mniBuscarporciudad = new javax.swing.JMenuItem();
        mniBuscarporapellido = new javax.swing.JMenuItem();
        mnuciudades = new javax.swing.JMenu();
        mniAgregarciudad = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        escritorio.setMaximumSize(new java.awt.Dimension(6, 0));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );

        mnucliente.setText("Cliente");

        mniAgregarcliente.setText("Agregar Cliente");
        mniAgregarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAgregarclienteActionPerformed(evt);
            }
        });
        mnucliente.add(mniAgregarcliente);

        mniBuscarcliente.setText("Buscar Cliente");
        mniBuscarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBuscarclienteActionPerformed(evt);
            }
        });
        mnucliente.add(mniBuscarcliente);

        mniBorrarcliente.setText("Borrar Cliente");
        mnucliente.add(mniBorrarcliente);

        jMenuBar1.add(mnucliente);

        mnudirectorio.setText("Directorio");

        mniBuscarporciudad.setText("Buscar Cliente por Ciudad");
        mniBuscarporciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBuscarporciudadActionPerformed(evt);
            }
        });
        mnudirectorio.add(mniBuscarporciudad);

        mniBuscarporapellido.setText("Buscar Telefono por Apellido");
        mniBuscarporapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBuscarporapellidoActionPerformed(evt);
            }
        });
        mnudirectorio.add(mniBuscarporapellido);

        jMenuBar1.add(mnudirectorio);

        mnuciudades.setText("Ciudades");

        mniAgregarciudad.setText("Agregar Ciudad");
        mniAgregarciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAgregarciudadActionPerformed(evt);
            }
        });
        mnuciudades.add(mniAgregarciudad);

        jMenuBar1.add(mnuciudades);

        jMenu4.setText("Salir");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void mniBuscarporciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBuscarporciudadActionPerformed
buscarciudad ciudad = new buscarciudad (NewJFrame1.DIRECTORIO);
abrirYCentrar(ciudad);        // TODO add your handling code here:
    }//GEN-LAST:event_mniBuscarporciudadActionPerformed

    private void mniAgregarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAgregarclienteActionPerformed
        AgregarCliente agregar = new AgregarCliente(NewJFrame1.DIRECTORIO);
        abrirYCentrar(agregar);
    }//GEN-LAST:event_mniAgregarclienteActionPerformed

    private void mniBuscarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBuscarclienteActionPerformed
        // TODO add your handling code here:
        BuscarCliente buscar = new BuscarCliente(NewJFrame1.DIRECTORIO);
        abrirYCentrar(buscar);
    }//GEN-LAST:event_mniBuscarclienteActionPerformed

    private void mniAgregarciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAgregarciudadActionPerformed
        AgregarCiudad ac = new AgregarCiudad(NewJFrame1.DIRECTORIO);
        abrirYCentrar(ac);
    }//GEN-LAST:event_mniAgregarciudadActionPerformed

    private void mniBuscarporapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBuscarporapellidoActionPerformed
BuscarApellido apellido = new BuscarApellido (NewJFrame1.DIRECTORIO);
abrirYCentrar(apellido);// TODO add your handling code here:
    }//GEN-LAST:event_mniBuscarporapellidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame1().setVisible(true));

    }

    private void abrirYCentrar(JInternalFrame frame) {
        escritorio.add(frame);
        frame.pack(); 
        frame.setVisible(true);

        int x = (escritorio.getWidth() - frame.getWidth()) / 2;
        int y = (escritorio.getHeight() - frame.getHeight()) / 2;
        frame.setLocation(x, y);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mniAgregarciudad;
    private javax.swing.JMenuItem mniAgregarcliente;
    private javax.swing.JMenuItem mniBorrarcliente;
    private javax.swing.JMenuItem mniBuscarcliente;
    private javax.swing.JMenuItem mniBuscarporapellido;
    private javax.swing.JMenuItem mniBuscarporciudad;
    private javax.swing.JMenu mnuciudades;
    private javax.swing.JMenu mnucliente;
    private javax.swing.JMenu mnudirectorio;
    // End of variables declaration//GEN-END:variables
}
