/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;

/**
 *
 * @author rodri
 */
public class NewJFrame1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame1.class.getName());

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnucliente = new javax.swing.JMenu();
        mniAgregarcliente = new javax.swing.JMenuItem();
        mniBuscarcliente = new javax.swing.JMenuItem();
        mniBorrarcliente = new javax.swing.JMenuItem();
        mnudirectorio = new javax.swing.JMenu();
        mniBuscarporciudad = new javax.swing.JMenuItem();
        mniBuscarporapellido = new javax.swing.JMenuItem();
        mnuciudades = new javax.swing.JMenu();
        mniAgregarciudad = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnucliente.setText("Cliente");

        mniAgregarcliente.setText("Agregar Cliente");
        mnucliente.add(mniAgregarcliente);

        mniBuscarcliente.setText("Buscar Cliente");
        mnucliente.add(mniBuscarcliente);

        mniBorrarcliente.setText("Borrar Cliente");
        mnucliente.add(mniBorrarcliente);

        jMenuBar1.add(mnucliente);

        mnudirectorio.setText("Directorio");

        mniBuscarporciudad.setText("Buscar Cliente por Ciudad");
        mniBuscarporciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBuscarporciudadActionPerformed(evt);
            }
        });
        mnudirectorio.add(mniBuscarporciudad);

        mniBuscarporapellido.setText("Buscar Telefono por Apellido");
        mnudirectorio.add(mniBuscarporapellido);

        jMenuBar1.add(mnudirectorio);

        mnuciudades.setText("Ciudades");

        mniAgregarciudad.setText("Agragar Ciudad");
        mnuciudades.add(mniAgregarciudad);

        jMenuBar1.add(mnuciudades);

        jMenu4.setText("Salir");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniBuscarporciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBuscarporciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniBuscarporciudadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mniAgregarciudad;
    private javax.swing.JMenuItem mniAgregarcliente;
    private javax.swing.JMenuItem mniBorrarcliente;
    private javax.swing.JMenuItem mniBuscarcliente;
    private javax.swing.JMenuItem mniBuscarporapellido;
    private javax.swing.JMenuItem mniBuscarporciudad;
    private javax.swing.JMenu mnuciudades;
    private javax.swing.JMenu mnucliente;
    private javax.swing.JMenu mnudirectorio;
    // End of variables declaration//GEN-END:variables
}
